---
- name: Create required output directories if not present
  tags: [build, provision]
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ fabric_dir }}"
  delegate_to: localhost
  run_once: true

- name: Set AVD facts
  tags: [build, provision]
  yaml_templates_to_facts:
    templates: "{{ templates.facts }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False

- name: Set AVD topology facts
  tags: [build, provision]
  yaml_templates_to_facts:
    templates: "{{ templates.topology_facts }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False

- name: Generate YAML file with hostvars (only for debugging)
  tags: [debug, never]
  template:
    src: debug/generate-debug-vars.j2
    dest: "{{ structured_dir }}/{{ inventory_hostname }}-debug-vars.yml"
    mode: 0664
  delegate_to: localhost
  changed_when: False

- name: Generate device configuration in structured format
  tags: [build, provision]
  yaml_templates_to_facts:
    root_key: structured_config
    templates: "{{ templates.structured_config }}"
  delegate_to: localhost
  check_mode: no
  changed_when: False

- name: Write device structured configuration to YAML file
  tags: [build, provision]
  template:
    src: generate-structured-config.j2
    dest: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
    mode: 0664
  delegate_to: localhost
  changed_when: False

- name: Include device structured configuration, that was previously generated.
  tags: [build, provision]
  include_vars: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
  delegate_to: localhost

- name: Generate fabric documentation
  tags: [build, provision, documentation]
  run_once: true
  delegate_to: localhost
  check_mode: no
  block:
    - name: Store checksum of existing fabric documentation
      ansible.builtin.stat:
        path: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
        checksum_algorithm: sha224
        get_attributes: no
        get_checksum: yes
        get_mime: no
      register: doc_stat_result
    - name: Generate fabric documentation in Markdown Format.
      template:
        src: fabric-documentation.j2
        dest: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
        mode: 0664
      changed_when: false
    - name: Generate TOC for fabric documentation
      add_toc:
        md_file: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
        skip_lines: 3
      register: toc_result
      changed_when: toc_result.checksum | default('1') != doc_stat_result.stat.checksum | default('0')

- name: Generate fabric point-to-point links summary in csv format.
  tags: [build, provision, documentation]
  template:
    src: documentation/fabric-p2p-links.j2
    dest: "{{ fabric_dir }}/{{ fabric_name }}-p2p-links.csv"
    mode: 0664
  delegate_to: localhost
  run_once: true
  check_mode: no

- name: Generate fabric topology in csv format.
  tags: [build, provision, documentation]
  template:
    src: documentation/fabric-topology.j2
    dest: "{{ fabric_dir }}/{{ fabric_name }}-topology.csv"
    mode: 0664
  delegate_to: localhost
  run_once: true
  check_mode: no
